### PR TITLE
feat: kafka docs

### PR DESCRIPTION
**Pull request by Calm-Rock**
- Raised docs for Local/VM(AWS/GCP/Azure)

### CODE REVIEW

**Comment by Calm-Rock** [comment]
Part of this issue - https://github.com/SigNoz/engineering-pod/issues/1584

**Comment by shivanshuraj1333** [comment]
add links to the receviers used here from upstream `kafkametrics`, `jmx`

```
  kafkametrics:
    brokers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    protocol_version: 2.0.0
    scrapers:
      - brokers
      - topics
      - consumers
  jmx/1:
    # configure the path where you installed opentelemetry-jmx-metrics jar
    jar_path: path/to/opentelemetry-jmx-metrics.jar #change this to the path to you opentelemetry-jmx-metrics jar file you downloaded above
    endpoint: service:jmx:rmi:///jndi/rmi://localhost:9991/jmxrmi
    target_system: jvm,kafka,kafka-consumer,kafka-producer
    collection_interval: 10s
    log_level: info
    resource_attributes:
      broker.name: broker1
  jmx/2:
    jar_path: ${PWD}/opentelemetry-jmx-metrics.jar
    endpoint: service:jmx:rmi:///jndi/rmi://localhost:9992/jmxrmi
    target_system: jvm,kafka,kafka-consumer,kafka-producer
    collection_interval: 10s
    log_level: info
    resource_attributes:
      broker.name: broker2
```

at the end, add some introduction about how to use messaging queue tab, and see data on SigNoz.

**Comment by shivanshuraj1333** [comment]
Can you confirm if you were able to set it up in your local environment?

**Comment by Calm-Rock** [comment]
> Can you confirm if you were able to set it up in your local environment?

No. I wasn't able to set it up in my local environment, probably because of memory issues. I will test it out in a VM. We can make these live for now. I will update them if they don't work on a VM.

**Review by shivanshuraj1333 — APPROVED** [review]
LGTM!
Thanks!!

**Review by ankit01-oss — APPROVED** [review]

**Pull request merged**
